---
- include: demo_playbook_iter_01.yml
- hosts: webservers
  remote_user: ec2-user
  vars:
    our_desired_package_name: git
  tasks:
  - name: Install our needed packages for AWS Linux
    yum: state=present name={{ our_desired_package_name }}
    sudo: yes
